name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build X64
      run: go build -o nifo-x64.exe .
      env:
        GOOS: windows
        GOARCH: amd64
       
    - name: Build ARM
      run: go build -o nifo-arm64.exe .
      env:
        GOOS: windows
        GOARCH: arm64

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "devbuild"
        prerelease: true
        title: "Commit Build"
        files: |
          nifo.exe

